"""
Prometheus metrics for the Sketch to Story pipeline.

This module defines all metric objects as module-level singletons so they can
be imported by both the FastAPI app and Celery worker without re-registering.

Prometheus's REGISTRY is a process-global singleton.  Importing this module
twice in the same process is safe — the `if name not in REGISTRY._names_to_collectors`
guard in prometheus_client prevents duplicate registration.

Usage in FastAPI (main.py)
--------------------------
    from monitoring.metrics_exporter import (
        pipeline_stage_duration_seconds,
        caption_word_count,
        story_panel_count,
        safety_score,
        jobs_total,
        queue_depth,
        update_queue_depth,
    )

Usage in Celery nodes
---------------------
    from monitoring.metrics_exporter import pipeline_stage_duration_seconds
    with pipeline_stage_duration_seconds.labels(stage="caption").time():
        caption = captioner.predict(...)

Queue depth refresh
-------------------
Call update_queue_depth(redis_client) before generating /metrics output.
It reads LLEN celery from Redis.  If Redis is unreachable the gauge is left
at its last known value.
"""

from __future__ import annotations

import logging

from prometheus_client import Counter, Gauge, Histogram, REGISTRY

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Helper: safe metric registration — avoids duplicate registration on reload
# ---------------------------------------------------------------------------

def _get_or_create_histogram(name: str, documentation: str, labelnames: list[str], buckets: list[float]) -> Histogram:
    """Return existing collector if already registered, otherwise create new."""
    if name in REGISTRY._names_to_collectors:  # noqa: SLF001
        return REGISTRY._names_to_collectors[name]  # noqa: SLF001
    return Histogram(name, documentation, labelnames=labelnames, buckets=buckets)


def _get_or_create_counter(name: str, documentation: str, labelnames: list[str]) -> Counter:
    if name in REGISTRY._names_to_collectors:  # noqa: SLF001
        return REGISTRY._names_to_collectors[name]  # noqa: SLF001
    return Counter(name, documentation, labelnames=labelnames)


def _get_or_create_gauge(name: str, documentation: str) -> Gauge:
    if name in REGISTRY._names_to_collectors:  # noqa: SLF001
        return REGISTRY._names_to_collectors[name]  # noqa: SLF001
    return Gauge(name, documentation)


# ---------------------------------------------------------------------------
# Metric definitions
# ---------------------------------------------------------------------------

# Stage latency — label: stage = caption | retrieve_style | generate_story |
#                                         check_safety | assemble | load_models
pipeline_stage_duration_seconds: Histogram = _get_or_create_histogram(
    "pipeline_stage_duration_seconds",
    "Duration of each comic-generation pipeline stage in seconds",
    labelnames=["stage"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
)

# Caption length distribution
caption_word_count: Histogram = _get_or_create_histogram(
    "caption_word_count",
    "Word count of captions generated by the BLIP captioner",
    labelnames=[],
    buckets=[0, 5, 10, 20, 30, 50],
)

# Panel count per story
story_panel_count: Histogram = _get_or_create_histogram(
    "story_panel_count",
    "Number of panels in a generated story",
    labelnames=[],
    buckets=[1, 2, 3, 4, 5, 6],
)

# Detoxify toxicity score (0–1) per panel
safety_score: Histogram = _get_or_create_histogram(
    "safety_score",
    "Detoxify toxicity score per panel (0=clean, 1=toxic)",
    labelnames=[],
    buckets=[0.0, 0.01, 0.05, 0.1, 0.2, 0.5, 1.0],
)

# Job lifecycle counter — label: status = queued | complete | failed
jobs_total: Counter = _get_or_create_counter(
    "jobs_total",
    "Total number of comic-generation jobs by terminal status",
    labelnames=["status"],
)

# Celery queue depth (updated on /metrics scrape)
queue_depth: Gauge = _get_or_create_gauge(
    "queue_depth_gauge",
    "Number of tasks currently waiting in the Celery Redis queue",
)


# ---------------------------------------------------------------------------
# Queue depth refresh helper
# ---------------------------------------------------------------------------

def update_queue_depth(redis_client) -> None:  # type: ignore[type-arg]
    """
    Refresh the queue_depth gauge from the Redis ``celery`` list length.

    Call this immediately before generating Prometheus output so the gauge
    reflects the current backlog.  Silently swallows any Redis errors.

    Parameters
    ----------
    redis_client:
        An active ``redis.Redis`` instance with ``decode_responses=True``.
    """
    try:
        depth = redis_client.llen("celery")
        queue_depth.set(depth)
        logger.debug("queue_depth updated: %d", depth)
    except Exception as exc:  # noqa: BLE001
        logger.debug("update_queue_depth skipped — %s", exc)
