apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace }}-limits
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: limitrange
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu | quote }}
        memory: {{ .Values.limitRange.defaultRequest.memory | quote }}
      default:
        cpu: {{ .Values.limitRange.defaultLimit.cpu | quote }}
        memory: {{ .Values.limitRange.defaultLimit.memory | quote }}
